# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ModelAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ip: str=None):  # noqa: E501
        """ModelAddress - a model defined in Swagger

        :param ip: The ip of this ModelAddress.  # noqa: E501
        :type ip: str
        """
        self.swagger_types = {
            'ip': str
        }

        self.attribute_map = {
            'ip': 'ip'
        }
        self._ip = ip

    @classmethod
    def from_dict(cls, dikt) -> 'ModelAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The model.Address of this ModelAddress.  # noqa: E501
        :rtype: ModelAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ip(self) -> str:
        """Gets the ip of this ModelAddress.


        :return: The ip of this ModelAddress.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip: str):
        """Sets the ip of this ModelAddress.


        :param ip: The ip of this ModelAddress.
        :type ip: str
        """

        self._ip = ip
