apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stakefish.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "stakefish.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "stakefish.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
          - secretRef:
              name: {{ .Values.app.secretName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
