replicaCount: 1

image:
  repository: my-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

redis:
  image: redis:alpine
  port: 6379

prometheus:
  image: prom/prometheus
  port: 9090
  scrapePath: /metrics

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
