replicaCount: 1

image:
  repository: thongngo3301/stakefish
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

redis:
  image: redis:alpine
  port: 6379

prometheus:
  image: prom/prometheus
  port: 9090
  scrapePath: /metrics
